DataX: src/Common/CharHelper.cpp File Reference
CharHelper.cpp File Reference
#include "CharHelper.h"
#include <cstring>
#include <strings.h>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include "Common/Typedefs.h"
#include "Common/Macros.h"
#include "Tracker/Debug.h"
Namespaces
NSCharHelper
Functions
static const char * SimpleFindSubStr (const char *pSubStart, size_t subLen, const char *pString, const char *pEnd, bool bReturnEndIfNotFound)
static void KMPCalcMaxCommonLengthTable (const char *pString, uint16_t *pArray, size_t len)
Calculate the max common matched length of the prefix and postfix sub string.
static const char * KMPFindSubStr (const char *pSubStart, size_t subLen, const char *pString, const char *pEnd, bool bReturnEndIfNotFound)
bool NSCharHelper::GetIntByString (const char *pString, size_t len, int *pOutNum)
bool NSCharHelper::GetStringByInt (int number, char *pBuffer, size_t buflen, size_t *pOutStringLen)
const char * NSCharHelper::FindSubStr (const char *pSub, size_t subLen, const char *pString, const char *pEnd, bool bReturnEndIfNotFound)
const char * NSCharHelper::FindChar (char target, const char *pString, const char *pEnd, bool bReturnEndIfNotFound)
bool NSCharHelper::CopyNChars (char *pDst, size_t dstLen, const char *pSrc, size_t *pOutLen)
bool NSCharHelper::IsHexChar (char ch)
char * NSCharHelper::Trim (char *pString)
const char * NSCharHelper::Trim (const char *pString, size_t len, size_t *pOutLen)
const char * NSCharHelper::TrimLeftSpace (const char *pString, const char *pEnd)
char * NSCharHelper::TrimRightSpace (char *pString)
const char * NSCharHelper::TrimRightSpace (const char *pBegin, const char *pEnd)
bool NSCharHelper::IsBlankString (const char *pString)
bool NSCharHelper::StringCompare (const char *pString1, const char *pString2)
bool NSCharHelper::StringCaseCompare (const char *pString1, const char *pString2)
int NSCharHelper::StringCompare1 (const char *pStr1, size_t len1, const char *pStr2, size_t len2, bool bCaseSensitive)
char * NSCharHelper::String2LowerCase (char *pString)
size_t NSCharHelper::StringNLength (const char *pStr, size_t len)
void NSCharHelper::Reverse (char *pString, size_t len)
Function Documentation
static void KMPCalcMaxCommonLengthTable (const char * pString, uint16_t * pArray, size_t len) static
Calculate the max common matched length of the prefix and postfix sub string.
This max length will determinate that how long step the pattern string should be move forward. This is the key concept of the KMP algorithm.
Here is the key point of the max common matched length. 1) P1 P2 P3, ..., P(k-1), P(k), ..., P(j-k), P(j-k+1), ..., P(j)
Parameters
pString The pattern string.
pArray The buffer to store the max common matched length data.
len The length of the string and the array.
Definition at line 64 of file CharHelper.cpp.
Referenced by KMPFindSubStr().
static const char* KMPFindSubStr (const char * pSubStart, size_t subLen, const char * pString, const char * pEnd, bool bReturnEndIfNotFound) static
Definition at line 84 of file CharHelper.cpp.
References KMPCalcMaxCommonLengthTable().
Referenced by NSCharHelper::FindSubStr().
static const char* SimpleFindSubStr (const char * pSubStart, size_t subLen, const char * pString, const char * pEnd, bool bReturnEndIfNotFound) static
Definition at line 19 of file CharHelper.cpp.
Referenced by NSCharHelper::FindSubStr().