DataX: src/CmdLine/CommandLine.cpp File Reference
CommandLine.cpp File Reference
#include "CommandLine.h"
#include <stdio.h>
#include <strings.h>
#include <cstring>
#include <cctype>
#include <cstdlib>
#include <readline/readline.h>
#include <readline/history.h>
#include "CmdHandler.h"
#include "LineArguments.h"
#include "DummyCmdHandler.h"
#include "IO/IOContext.h"
#include "Common/CharHelper.h"
#include "Tracker/Debug.h"
Functions
static char * GenerateRequestHint (const char *pText, int state)
static char * GenerateCommandHint (const char *pText, int state)
static char ** TextCompletion (const char *pText, int start, int end)
Function Documentation
static char* GenerateCommandHint (const char * pText, int state) static
Definition at line 39 of file CommandLine.cpp.
Referenced by TextCompletion().
static char* GenerateRequestHint (const char * pText, int state) static
Definition at line 33 of file CommandLine.cpp.
Referenced by TextCompletion().
static char** TextCompletion (const char * pText, int start, int end) static
Definition at line 45 of file CommandLine.cpp.
References GenerateCommandHint(), GenerateRequestHint(), GetErrorPhrase(), NSCharHelper::TrimLeftSpace(), and NSCharHelper::TrimRightSpace().