DataX: src/App/CookieApp/main.cpp File Reference
main.cpp File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <vector>
#include "HTTP/HttpCookieDB.h"
#include "HTTP/HttpCookieManager.h"
#include "Common/Typedefs.h"
#include "Common/ByteData.h"
#include "CmdLine/CommandLine.h"
#include "CmdLine/CommonCmdHandler.h"
#include "CookieCmdHandler.h"
Functions
static bool CreateCommandHandlers (vector< CCmdHandler * > &handlers, CHttpCookieDB &db)
static void DestroyCommandHandlers (vector< CCmdHandler * > &handlers)
static bool ParsePath (const char *pPath, char **pOutBaseName, char **pOutFileName)
static void Usage (const char *pProgName)
int main (int argc, char *argv[])
Function Documentation
static bool CreateCommandHandlers (vector< CCmdHandler * > & handlers, CHttpCookieDB & db) static
Definition at line 19 of file main.cpp.
Referenced by main().
static void DestroyCommandHandlers (vector< CCmdHandler * > & handlers) static
Definition at line 34 of file main.cpp.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 96 of file main.cpp.
References CreateCommandHandlers(), DestroyCommandHandlers(), ParsePath(), and Usage().
static bool ParsePath (const char * pPath, char ** pOutBaseName, char ** pOutFileName) static
Definition at line 44 of file main.cpp.
Referenced by main().
static void Usage (const char * pProgName) static
Definition at line 91 of file main.cpp.
Referenced by main().