DataX: src/Tracker/Debug.cpp File Reference
Debug.cpp File Reference
#include "Debug.h"
#include <cstdarg>
#include <cstdio>
#include <cstdlib>
#include <cctype>
#include <syslog.h>
#include <unistd.h>
#include <signal.h>
#include <execinfo.h>
#include <dlfcn.h>
#include <cxxabi.h>
#include "Time.h"
#include "Common/Macros.h"
#include "Thread/Thread.h"
Functions
static void HandleCrashSignal (int signalNo, siginfo_t *pInfo, void *context)
void InitializeDebug ()
void Assert (const char *pExpression, const char *pFilename, int lineno,...)
void OutputTrace (const char *format,...)
void OutputStringTrace (const char *pStr, size_t len)
void OutputCallStack ()
void DumpBytes (void *pData, size_t len)
void DumpString (char *pStr, size_t len)
Function Documentation
void Assert (const char * pExpression, const char * pFilename, int lineno, ...)
Definition at line 206 of file Debug.cpp.
References GetProcessElapseTime(), OutputCallStack(), and OutputTrace().
void DumpBytes (void * pData, size_t len)
Definition at line 293 of file Debug.cpp.
void DumpString (char * pStr, size_t len)
Definition at line 317 of file Debug.cpp.
static void HandleCrashSignal (int signalNo, siginfo_t * pInfo, void * context) static
Definition at line 22 of file Debug.cpp.
References OutputCallStack(), and OutputTrace().
Referenced by InitializeDebug().
void InitializeDebug ()
Definition at line 192 of file Debug.cpp.
References HandleCrashSignal().
Referenced by main().
void OutputCallStack ()
Definition at line 256 of file Debug.cpp.
References OutputTrace().
Referenced by Assert(), and HandleCrashSignal().
void OutputStringTrace (const char * pStr, size_t len)
Definition at line 241 of file Debug.cpp.
References OutputTrace().
void OutputTrace (const char * format, ...)
Definition at line 231 of file Debug.cpp.
Referenced by Assert(), HandleCrashSignal(), OutputCallStack(), and OutputStringTrace().