DataX: src/Network/Domain.cpp File Reference
Domain.cpp File Reference
#include "Domain.h"
#include <cctype>
#include <set>
#include "Common/Macros.h"
#include "Common/CharHelper.h"
#include "Tracker/Debug.h"
Namespaces
NSInternetDomain
Functions
static int MakeSectionIndex (const char *pDomainStr, const char **pIdxBuf, size_t idxBufLen, size_t *pOutDomainStrLen=NULL)
static int FindPublicSuffix (const char **pIndex, size_t indexLen)
static bool IsConuntryCode (const char *pStr, size_t len=0)
static bool IsGeneralTopDomain (const char *pStr, size_t len=0)
bool NSInternetDomain::ParseString (const char *pDomainStr, DomainDesc *pOutDesc)
bool NSInternetDomain::IsMatch (DomainDesc *pDesc, const char *pBenchMarkDomainStr)
Function Documentation
static int FindPublicSuffix (const char ** pIndex, size_t indexLen) static
Definition at line 161 of file Domain.cpp.
References IsConuntryCode(), and IsGeneralTopDomain().
Referenced by NSInternetDomain::IsMatch(), and NSInternetDomain::ParseString().
static bool IsConuntryCode (const char * pStr, size_t len = 0) static
Definition at line 203 of file Domain.cpp.
Referenced by FindPublicSuffix().
static bool IsGeneralTopDomain (const char * pStr, size_t len = 0) static
Definition at line 308 of file Domain.cpp.
References NSCharHelper::StringCaseCompare().
Referenced by FindPublicSuffix().
static int MakeSectionIndex (const char * pDomainStr, const char ** pIdxBuf, size_t idxBufLen, size_t * pOutDomainStrLen = NULL) static
Definition at line 123 of file Domain.cpp.
Referenced by NSInternetDomain::IsMatch(), and NSInternetDomain::ParseString().