DataX: NSSendRecv Namespace Reference
NSSendRecv Namespace Reference
Functions
bool Send (NSCliMsg::Message *pMsg, CIOContext &io)
NSCliMsg::Message * Recv (uint16_t session, CIOContext &io, int timeout)
NSCliMsg::Message * Recv (uint16_t session, CIOContext &io, uint8_t *pBuf, size_t len, int timeout)
NSCliMsg::Message * SendAndRecv (NSCliMsg::Message *pMsg, CIOContext &io, uint8_t *pBuf, size_t len, int timeout)
Function Documentation
NSCliMsg::Message* NSSendRecv::Recv (uint16_t session, CIOContext & io, int timeout)
Definition at line 19 of file SendRecv.cpp.
Referenced by SendAndRecv().
NSCliMsg::Message* NSSendRecv::Recv (uint16_t session, CIOContext & io, uint8_t * pBuf, size_t len, int timeout)
Definition at line 79 of file SendRecv.cpp.
bool NSSendRecv::Send (NSCliMsg::Message * pMsg, CIOContext & io)
Definition at line 11 of file SendRecv.cpp.
Referenced by SendAndRecv().
NSCliMsg::Message* NSSendRecv::SendAndRecv (NSCliMsg::Message * pMsg, CIOContext & io, uint8_t * pBuf, size_t len, int timeout)
Definition at line 139 of file SendRecv.cpp.
References Recv(), and Send().