DataX: NSCharHelper Namespace Reference
NSCharHelper Namespace Reference
Functions
bool GetIntByString (const char *pString, size_t len, int *pOutNum)
bool GetStringByInt (int number, char *pBuffer, size_t buflen, size_t *pOutStringLen)
const char * FindSubStr (const char *pSub, size_t subLen, const char *pString, const char *pEnd, bool bReturnEndIfNotFound)
const char * FindChar (char target, const char *pString, const char *pEnd, bool bReturnEndIfNotFound)
bool CopyNChars (char *pDst, size_t dstLen, const char *pSrc, size_t *pOutLen)
bool IsHexChar (char ch)
char * Trim (char *pString)
const char * Trim (const char *pString, size_t len, size_t *pOutLen)
const char * TrimLeftSpace (const char *pString, const char *pEnd)
char * TrimRightSpace (char *pString)
const char * TrimRightSpace (const char *pBegin, const char *pEnd)
bool IsBlankString (const char *pString)
bool StringCompare (const char *pString1, const char *pString2)
bool StringCaseCompare (const char *pString1, const char *pString2)
int StringCompare1 (const char *pStr1, size_t len1, const char *pStr2, size_t len2, bool bCaseSensitive)
char * String2LowerCase (char *pString)
size_t StringNLength (const char *pStr, size_t len)
void Reverse (char *pString, size_t len)
Function Documentation
bool NSCharHelper::CopyNChars (char * pDst, size_t dstLen, const char * pSrc, size_t * pOutLen)
Definition at line 294 of file CharHelper.cpp.
Referenced by NSUriCharUtils::IsReservedChar().
const char* NSCharHelper::FindChar (char target, const char * pString, const char * pEnd, bool bReturnEndIfNotFound)
Definition at line 259 of file CharHelper.cpp.
Referenced by FindSubStr().
const char* NSCharHelper::FindSubStr (const char * pSub, size_t subLen, const char * pString, const char * pEnd, bool bReturnEndIfNotFound)
Definition at line 239 of file CharHelper.cpp.
References FindChar(), KMPFindSubStr(), and SimpleFindSubStr().
bool NSCharHelper::GetIntByString (const char * pString, size_t len, int * pOutNum)
Definition at line 173 of file CharHelper.cpp.
Referenced by NSUriCharUtils::IsReservedChar().
bool NSCharHelper::GetStringByInt (int number, char * pBuffer, size_t buflen, size_t * pOutStringLen)
Definition at line 200 of file CharHelper.cpp.
Referenced by NSUriCharUtils::IsReservedChar().
bool NSCharHelper::IsBlankString (const char * pString)
Definition at line 432 of file CharHelper.cpp.
bool NSCharHelper::IsHexChar (char ch)
Definition at line 309 of file CharHelper.cpp.
Referenced by NSUriCharUtils::IsReservedChar().
void NSCharHelper::Reverse (char * pString, size_t len)
Definition at line 509 of file CharHelper.cpp.
char* NSCharHelper::String2LowerCase (char * pString)
Definition at line 482 of file CharHelper.cpp.
bool NSCharHelper::StringCaseCompare (const char * pString1, const char * pString2)
Definition at line 448 of file CharHelper.cpp.
Referenced by IsGeneralTopDomain().
bool NSCharHelper::StringCompare (const char * pString1, const char * pString2)
Definition at line 443 of file CharHelper.cpp.
int NSCharHelper::StringCompare1 (const char * pStr1, size_t len1, const char * pStr2, size_t len2, bool bCaseSensitive)
Definition at line 453 of file CharHelper.cpp.
size_t NSCharHelper::StringNLength (const char * pStr, size_t len)
Definition at line 496 of file CharHelper.cpp.
char* NSCharHelper::Trim (char * pString)
Definition at line 314 of file CharHelper.cpp.
const char* NSCharHelper::Trim (const char * pString, size_t len, size_t * pOutLen)
Definition at line 342 of file CharHelper.cpp.
const char* NSCharHelper::TrimLeftSpace (const char * pString, const char * pEnd)
Definition at line 381 of file CharHelper.cpp.
Referenced by TextCompletion().
char* NSCharHelper::TrimRightSpace (char * pString)
Definition at line 407 of file CharHelper.cpp.
Referenced by TextCompletion().
const char* NSCharHelper::TrimRightSpace (const char * pBegin, const char * pEnd)
Definition at line 419 of file CharHelper.cpp.