DataX: NSUriCharUtils Namespace Reference
NSUriCharUtils Namespace Reference
Functions
bool IsUnreservedChar (char c)
bool IsSubDelim (char c)
bool IsGeneralDelim (char c)
bool IsPChar (char c)
pchar = unreserved / pct-encoded / sub-delims / ":" / "@"
bool IsReservedChar (char c)
Function Documentation
bool NSUriCharUtils::IsGeneralDelim (char c) inline
Definition at line 39 of file URI.cpp.
Referenced by IsReservedChar().
bool NSUriCharUtils::IsPChar (char c) inline
pchar = unreserved / pct-encoded / sub-delims / ":" / "@"
Definition at line 48 of file URI.cpp.
References IsSubDelim(), and IsUnreservedChar().
Referenced by IsReservedChar().
bool NSUriCharUtils::IsReservedChar (char c) inline
Definition at line 53 of file URI.cpp.
References NSCharHelper::CopyNChars(), NSCharHelper::GetIntByString(), NSNetworkAddress::GetIPAddress(), NSCharHelper::GetStringByInt(), IsGeneralDelim(), NSCharHelper::IsHexChar(), IsPChar(), IsSubDelim(), and IsUnreservedChar().
bool NSUriCharUtils::IsSubDelim (char c) inline
Definition at line 33 of file URI.cpp.
Referenced by IsPChar(), and IsReservedChar().
bool NSUriCharUtils::IsUnreservedChar (char c) inline
Definition at line 28 of file URI.cpp.
Referenced by IsPChar(), and IsReservedChar().