#
# See the file LICENSE for redistribution information.
#
# Copyright (c) 2015-2018, Yuan Qin <yuanqin2000 at outlook dot com>
# All rights reserved.
#

include $(COMMON_MK)

exe:
	$(MAKE) -C CoreApp exe
	$(MAKE) -C CookieApp exe
	$(MAKE) -C CtrlApp exe

.PHONY: exe