#
# See the file LICENSE for redistribution information.
#
# Copyright (c) 2015-2018, Yuan Qin <yuanqin2000 at outlook dot com>
# All rights reserved.
#

include $(DEFINES_MK)
include $(COMMON_MK)

all:
	$(MAKE) -C $(SOURCE_ROOT)App exe

.PHONY:	all
